// Acervo Vasco — dados de 2026
// Lista dos 30 jogos exibidos no print, mais o detalhe completo da partida 13/05.

window.SEASON_2026 = {
  ano: 2026,
  tecnicos: [
    { nome: "Fernando Diniz", jogos: 11, periodo: "15/01 – 22/02" },
    { nome: "Bruno Lazaroni", interino: true, jogos: 2, periodo: "26/02 – 01/03" },
    { nome: "Renato Gaúcho", jogos: 17, periodo: "12/03 – atual" },
  ],
  capitao_atual: "Léo Jardim",
  resumo: {
    jogos: 30, vitorias: 11, empates: 11, derrotas: 8,
    gols_pro: 42, gols_contra: 32, saldo: 10, aproveitamento: 48.9,
    media_pro: 1.4, media_contra: 1.07,
    maior_invicta: 6, maior_jejum: 5,
    publico_pagante: 112152, publico_presente: 116986, renda: 7697690.00,
  },
  // ordenados por data, mais antigo primeiro
  jogos: [
    { id: 1,  data: "15/01/2026", local: "casa", competicao: "Campeonato Carioca",         adversario: "Maricá",          resultado: "V", placar: [4,2], tecnico: "Fernando Diniz",         estadio: "São Januário",       publico: 12340 },
    { id: 2,  data: "18/01/2026", local: "casa", competicao: "Campeonato Carioca",         adversario: "Nova Iguaçu",     resultado: "E", placar: [0,0], tecnico: "Fernando Diniz",         estadio: "São Januário",       publico:  8210 },
    { id: 3,  data: "21/01/2026", local: "fora", competicao: "Campeonato Carioca",         adversario: "Flamengo-RJ",     resultado: "D", placar: [0,1], tecnico: "Fernando Diniz",         estadio: "Maracanã",           publico: 51230 },
    { id: 4,  data: "25/01/2026", local: "fora", competicao: "Campeonato Carioca",         adversario: "Boavista-RJ",     resultado: "V", placar: [3,0], tecnico: "Fernando Diniz",         estadio: "Elcyr Resende",      publico:  3120 },
    { id: 5,  data: "29/01/2026", local: "fora", competicao: "Campeonato Brasileiro Série A", adversario: "Mirassol",     resultado: "D", placar: [1,2], tecnico: "Fernando Diniz",         estadio: "Maião",              publico:  9420 , rodada: 1, posicao: 14 },
    { id: 6,  data: "02/02/2026", local: "fora", competicao: "Campeonato Carioca",         adversario: "Madureira-RJ",    resultado: "E", placar: [0,0], tecnico: "Fernando Diniz",         estadio: "Conselheiro Galvão", publico:  4080 },
    { id: 7,  data: "05/02/2026", local: "casa", competicao: "Campeonato Brasileiro Série A", adversario: "Chapecoense", resultado: "E", placar: [1,1], tecnico: "Fernando Diniz",         estadio: "São Januário",       publico: 18420 , rodada: 2, posicao: 14 },
    { id: 8,  data: "08/02/2026", local: "casa", competicao: "Campeonato Carioca",         adversario: "Botafogo",        resultado: "V", placar: [2,0], tecnico: "Fernando Diniz",         estadio: "São Januário",       publico: 19800 },
    { id: 9,  data: "11/02/2026", local: "casa", competicao: "Campeonato Brasileiro Série A", adversario: "Bahia-BA",    resultado: "D", placar: [0,1], tecnico: "Fernando Diniz",         estadio: "São Januário",       publico: 16200 , rodada: 3, posicao: 17 },
    { id:10,  data: "14/02/2026", local: "casa", competicao: "Campeonato Carioca",         adversario: "Volta Redonda-RJ",resultado: "E", placar: [1,1], tecnico: "Fernando Diniz",         estadio: "São Januário",       publico:  9540 },
    { id:11,  data: "22/02/2026", local: "casa", competicao: "Campeonato Carioca",         adversario: "Fluminense-RJ",   resultado: "D", placar: [0,1], tecnico: "Fernando Diniz",         estadio: "Maracanã",           publico: 47120 },
    { id:12,  data: "26/02/2026", local: "fora", competicao: "Campeonato Brasileiro Série A", adversario: "Santos",      resultado: "D", placar: [1,2], tecnico: "Bruno Lazaroni (interino)",estadio: "Vila Belmiro",       publico: 14100 , rodada: 4, posicao: 19 },
    { id:13,  data: "01/03/2026", local: "fora", competicao: "Campeonato Carioca",         adversario: "Fluminense-RJ",   resultado: "E", placar: [1,1], tecnico: "Bruno Lazaroni (interino)",estadio: "Maracanã",           publico: 32100 },
    { id:14,  data: "12/03/2026", local: "casa", competicao: "Campeonato Brasileiro Série A", adversario: "Palmeiras-SP",resultado: "V", placar: [2,1], tecnico: "Renato Gaúcho",          estadio: "São Januário",       publico: 21300 , rodada: 5, posicao: 14 },
    { id:15,  data: "15/03/2026", local: "fora", competicao: "Campeonato Brasileiro Série A", adversario: "Cruzeiro-MG", resultado: "E", placar: [3,3], tecnico: "Renato Gaúcho",          estadio: "Mineirão",           publico: 38200 , rodada: 6, posicao: 13 },
    { id:16,  data: "18/03/2026", local: "casa", competicao: "Campeonato Brasileiro Série A", adversario: "Fluminense-RJ",resultado:"V",placar: [3,2], tecnico: "Renato Gaúcho",          estadio: "Maracanã",           publico: 52800 , rodada: 7, posicao: 10 },
    { id:17,  data: "22/03/2026", local: "casa", competicao: "Campeonato Brasileiro Série A", adversario: "Grêmio-RS",   resultado: "V", placar: [2,1], tecnico: "Renato Gaúcho",          estadio: "São Januário",       publico: 19120 , rodada: 8, posicao: 8 },
    { id:18,  data: "01/04/2026", local: "fora", competicao: "Campeonato Brasileiro Série A", adversario: "Coritiba-PR", resultado: "E", placar: [1,1], tecnico: "Renato Gaúcho",          estadio: "Couto Pereira",      publico: 17400 , rodada: 9, posicao: 9 },
    { id:19,  data: "04/04/2026", local: "casa", competicao: "Campeonato Brasileiro Série A", adversario: "Botafogo",    resultado: "D", placar: [1,2], tecnico: "Renato Gaúcho",          estadio: "Maracanã",           publico: 48200 , rodada: 10, posicao: 11 },
    { id:20,  data: "07/04/2026", local: "fora", competicao: "Copa Sul-Americana",          adversario: "Barracas Central",resultado: "E", placar: [0,0], tecnico: "Renato Gaúcho",         estadio: "Tomás Adolfo Ducó",  publico:  9200 },
    { id:21,  data: "11/04/2026", local: "fora", competicao: "Campeonato Brasileiro Série A", adversario: "Remo",        resultado: "E", placar: [1,1], tecnico: "Renato Gaúcho",          estadio: "Mangueirão",         publico: 28400 , rodada: 11, posicao: 11 },
    { id:22,  data: "14/04/2026", local: "casa", competicao: "Copa Sul-Americana",          adversario: "Audax italiano", resultado: "D", placar: [1,2], tecnico: "Renato Gaúcho",          estadio: "São Januário",       publico: 14100 },
    { id:23,  data: "18/04/2026", local: "casa", competicao: "Campeonato Brasileiro Série A", adversario: "São Paulo-SP",resultado: "V", placar: [2,1], tecnico: "Renato Gaúcho",          estadio: "São Januário",       publico: 22850 , rodada: 12, posicao: 9 },
    { id:24,  data: "21/04/2026", local: "fora", competicao: "Copa do Brasil",              adversario: "Paysandu-PA",     resultado: "V", placar: [2,0], tecnico: "Renato Gaúcho",          estadio: "Curuzu",             publico: 18200 },
    { id:25,  data: "26/04/2026", local: "fora", competicao: "Campeonato Brasileiro Série A", adversario: "Corinthians",resultado: "D", placar: [0,1], tecnico: "Renato Gaúcho",          estadio: "Neo Química Arena",  publico: 41200 , rodada: 13, posicao: 10 },
    { id:26,  data: "30/04/2026", local: "casa", competicao: "Copa Sul-Americana",          adversario: "Olimpia",         resultado: "V", placar: [3,0], tecnico: "Renato Gaúcho",          estadio: "São Januário",       publico: 19800 },
    { id:27,  data: "03/05/2026", local: "fora", competicao: "Campeonato Brasileiro Série A", adversario: "Flamengo-RJ",resultado: "E", placar: [2,2], tecnico: "Renato Gaúcho",          estadio: "Maracanã",           publico: 62400 , rodada: 14, posicao: 10 },
    { id:28,  data: "06/05/2026", local: "fora", competicao: "Copa Sul-Americana",          adversario: "Audax italiano", resultado: "V", placar: [2,1], tecnico: "Renato Gaúcho",          estadio: "El Teniente",        publico:  8900 },
    { id:29,  data: "10/05/2026", local: "casa", competicao: "Campeonato Brasileiro Série A", adversario: "Athletico-PR",resultado: "V", placar: [1,0], tecnico: "Renato Gaúcho",          estadio: "São Januário",       publico: 20100 , rodada: 15, posicao: 8 },
    { id:30,  data: "13/05/2026", local: "casa", competicao: "Copa do Brasil",              adversario: "Paysandu-PA",     resultado: "E", placar: [2,2], tecnico: "Renato Gaúcho",          estadio: "São Januário",       publico: 16653, detalhe: true },
  ],
  // artilharia agregada do ano — derivada do acervo
  artilheiros: [
    { nome: "Brenner",       gols: 8 },
    { nome: "David",         gols: 6 },
    { nome: "Johan Rojas",   gols: 5 },
    { nome: "Adson",         gols: 4 },
    { nome: "Andrés Gómez",  gols: 4 },
    { nome: "Thiago Mendes", gols: 3 },
    { nome: "Lucas Piton",   gols: 3 },
    { nome: "Nuno Moreira",  gols: 3 },
    { nome: "Marino",        gols: 2 },
    { nome: "Claudio Spinelli", gols: 2 },
    { nome: "outros",        gols: 2 },
  ],
};

// Detalhe completo da partida 30 (13/05/2026 — Vasco 2x2 Paysandu-PA)
window.PARTIDA_PAYSANDU = {
  id: 30,
  data: "13/05/2026",
  adversario: "Paysandu-PA",
  competicao: "Copa do Brasil",
  fase: "5ª fase — volta · oitavas",
  local: "casa",
  estadio: "São Januário",
  horario: "19:00",
  tecnico: "Renato Gaúcho",
  capitao: "Thiago Mendes",
  placar: { vasco: 2, adversario: 2 },
  agregado: { vasco: 4, adversario: 2, classificado: "Vasco" },
  gols_vasco: [
    { nome: "Johan Rojas",   minuto: 35, periodo: "1T", penalti: true },
    { nome: "Thiago Mendes", minuto: 41, periodo: "1T" },
  ],
  gols_adversario: [
    { nome: "Thayllon",  minuto: 47, periodo: "1T" },
    { nome: "Saldivia",  minuto:  1, periodo: "2T", contra: true },
  ],
  cartoes_amarelos_vasco: ["Lucas Freitas", "Nuno Moreira"],
  cartoes_vermelhos_vasco: [{ nome: "Thiago Mendes", minuto: 44, periodo: "2T", motivo: "cotovelada em Caio Mello" }],
  publico_pagante: 15775,
  publico_presente: 16653,
  renda: 1081866.00,
  arbitragem: {
    arbitro: "Braulio da Silva Machado",
    auxiliares: ["Thiaggo Americano Labes", "Henrique Neu Ribeiro"],
    var: "Rafael Traci",
  },
  escalacao: {
    formacao: "4-4-2",
    titulares_por_posicao: {
      Goleiro:           ["Léo Jardim"],
      "Lateral-Direito": ["Paulo Henrique"],
      Zagueiro:          ["Saldivia", "Lucas Freitas"],
      "Lateral-Esquerdo":["Lucas Piton"],
      Volante:           ["Cauan Barros", "Thiago Mendes"],
      "Meio-Campista":   ["Johan Rojas", "Marino"],
      Atacante:          ["David", "Brenner"],
    },
    reservas: ["Daniel Fuzato","Puma Rodríguez","Tche Tche","Matheus França","Andrés Gómez","Nuno Moreira","Hugo Moura","Adson","Pablo","Walace Falcão","Claudio Spinelli","JP"],
    substituicoes: [
      { sai: "Paulo Henrique", entra: "Puma Rodríguez",   minuto:  5, periodo: "2T" },
      { sai: "Marino",         entra: "Adson",             minuto: 15, periodo: "2T" },
      { sai: "David",          entra: "Claudio Spinelli",  minuto: 15, periodo: "2T" },
      { sai: "Brenner",        entra: "Andrés Gómez",      minuto: 15, periodo: "2T" },
      { sai: "Johan Rojas",    entra: "Nuno Moreira",      minuto: 25, periodo: "2T" },
    ],
    nao_relacionados: ["Alison","Allan Vitor","Andrey Fernandes","Avellar","Breno Vereza","Bruno André","Carlos Cuesta","Gustavo Guimarães","João Vitor","Juninho","Lukas Zucarello","Phillipe Gabriel","Ramon Rique","Robert Renan","Samuel Jesus"],
    lesionados: ["Jair","Mateus Carvalho","Cuiabano"],
    suspensos: [],
    servindo_selecao: [],
  },
  observacao: "Vasco empatou com o Paysandu em 2 a 2 em São Januário, pela volta da 5ª fase da Copa do Brasil 2026, e avançou às oitavas pelo agregado de 4 a 2. Thiago Mendes era o capitão e foi expulso aos 44'/2T por cotovelada em Caio Mello. Foi respeitado 1 minuto de silêncio em homenagem póstuma a torcedores do Vasco.",
};
