// Acervo Vasco — Aba Geral: KPIs + Artilheiros + Carrascos (gols contra)
// Dados do print do app legado.

window.GERAL_TOTAIS = {
  jogos: 1759, vitorias: 768, empates: 470, derrotas: 521,
  gp: 2677, gc: 2145, saldo: 532, aprov: 52.6,
  media_gp: 1.52, media_gc: 1.22,
  maior_invicta: 34, maior_derrotas: 7,
};

window.ARTILHEIROS_VASCO = [
  { nome:"Romário", gols:197 },
  { nome:"Nenê", gols:63 },
  { nome:"Pablo Vegetti", gols:60 },
  { nome:"Élton", gols:52 },
  { nome:"Leandro Amaral", gols:51 },
  { nome:"Edmundo", gols:47 },
  { nome:"Ramon", gols:44 },
  { nome:"Germán Cano", gols:43 },
  { nome:"Alecsandro", gols:39 },
  { nome:"Morais", gols:38 },
  { nome:"Yago Pikachu", gols:37 },
  { nome:"Gol contra", gols:36 },
  { nome:"Thalles", gols:36 },
  { nome:"Juninho", gols:35 },
  { nome:"Valdir", gols:35 },
  { nome:"Alex Dias", gols:33 },
  { nome:"Bernardo", gols:33 },
  { nome:"Dedé", gols:31 },
  { nome:"Éder Luís", gols:30 },
  { nome:"Diego Souza", gols:30 },
  { nome:"Juninho Paulista", gols:29 },
  { nome:"Euller", gols:28 },
  { nome:"Souza", gols:28 },
  { nome:"Petkovic", gols:28 },
  { nome:"Carlos Alberto", gols:26 },
  { nome:"Gabriel Pec", gols:26 },
  { nome:"Marcelinho", gols:25 },
  { nome:"Rayan", gols:25 },
  { nome:"Felipe", gols:24 },
  { nome:"Edmilson", gols:24 },
  { nome:"Viola", gols:23 },
  { nome:"Abedi", gols:23 },
  { nome:"Alan Kardec", gols:23 },
  { nome:"Philippe Coutinho", gols:22 },
  { nome:"Alex Teixeira", gols:21 },
  { nome:"Riascos", gols:20 },
  { nome:"Léo Lima", gols:19 },
  { nome:"Fellipe Bastos", gols:19 },
  { nome:"Rodrigo", gols:19 },
  { nome:"Cadu", gols:18 },
  { nome:"Gilberto", gols:17 },
  { nome:"Pedrinho", gols:17 },
  { nome:"Nílton", gols:17 },
  { nome:"Ânderson", gols:16 },
  { nome:"Douglas", gols:16 },
  { nome:"Andrés Ríos", gols:16 },
  { nome:"Raniel", gols:16 },
  { nome:"Valdiram", gols:14 },
  { nome:"Jean", gols:14 },
  { nome:"Fágner", gols:14 },
  { nome:"Tenorio", gols:14 },
  { nome:"André", gols:13 },
  { nome:"Maxi López", gols:12 },
  { nome:"Pedro Raul", gols:12 },
  { nome:"Marrony", gols:12 },
  { nome:"Talles Magno", gols:11 },
  { nome:"Marquinhos Gabriel", gols:11 },
  { nome:"Renato", gols:10 },
  { nome:"Bruno Mezenga", gols:10 },
];

window.CARRASCOS = [
  { nome:"Bruno Henrique", gols:3 },
  { nome:"Patrick Mercado", gols:3 },
  { nome:"Flaco López", gols:3 },
  { nome:"João Victor (contra)", gols:2 },
  { nome:"Yuri Alberto", gols:2 },
  { nome:"Memphis Depay", gols:2 },
  { nome:"Pedro Raul", gols:2 },
  { nome:"Christian", gols:2 },
  { nome:"Vitor Roque", gols:2 },
  { nome:"Junior Paredes", gols:2 },
  { nome:"Renato Kayzer", gols:2 },
  { nome:"Arthur Cabral", gols:2 },
  { nome:"Nenê", gols:2 },
  { nome:"Alex Telles", gols:2 },
  { nome:"Carlos Vinicius", gols:2 },
  { nome:"Dudu", gols:2 },
  { nome:"Kevin Serna", gols:2 },
  { nome:"Neymar", gols:2 },
  { nome:"Saldivia (contra)", gols:2 },
  { nome:"Pena", gols:1 },
  { nome:"Argel", gols:1 },
  { nome:"Euller", gols:1 },
  { nome:"Arce", gols:1 },
  { nome:"Valenzuela", gols:1 },
  { nome:"Marcelo Fernandes", gols:1 },
  { nome:"Olalde", gols:1 },
  { nome:"André Silva", gols:1 },
  { nome:"Sidney", gols:1 },
  { nome:"Zé Vitor", gols:1 },
  { nome:"Joãozinho", gols:1 },
  { nome:"Bruno Santos", gols:1 },
  { nome:"Thiago Silva", gols:1 },
  { nome:"Germán Cano", gols:1 },
  { nome:"Everton Cebolinha", gols:1 },
  { nome:"Luiz Araújo", gols:1 },
  { nome:"Barreal", gols:1 },
  { nome:"Rodriguez", gols:1 },
  { nome:"Castro", gols:1 },
  { nome:"Cabrera", gols:1 },
  { nome:"Hugo Moura (contra)", gols:1 },
  { nome:"Gabriel Boschilia", gols:1 },
  { nome:"Gerardo Padrón", gols:1 },
  { nome:"Raudy Guerrero", gols:1 },
  { nome:"Ramiro Carrera", gols:1 },
  { nome:"Ademilson", gols:1 },
  { nome:"Guga", gols:1 },
  { nome:"Pablo Vegetti (contra)", gols:1 },
  { nome:"Guilherme Lopes", gols:1 },
  { nome:"Isidro Pitta", gols:1 },
  { nome:"Ryan Francisco", gols:1 },
  { nome:"Nathan Fernandes", gols:1 },
  { nome:"Mateo Carabajal", gols:1 },
];
