// Acervo Vasco — dados de técnicos (do print do app legado)

window.TECNICOS = [
  { nome:"Renato Gaúcho",          jogos:151, casa:75, fora:76, v:68, e:45, d:38, gp:301, gc:221, saldo:80, aprov:55.0, maior_goleador:{nome:"Romário",gols:54} },
  { nome:"Jorginho",               jogos:122, casa:62, fora:60, v:55, e:36, d:31, gp:163, gc:132, saldo:31, aprov:54.9, maior_goleador:{nome:"Nenê",gols:32} },
  { nome:"Celso Roth",              jogos:122, casa:61, fora:61, v:49, e:30, d:43, gp:168, gc:161, saldo:7,  aprov:48.4, maior_goleador:{nome:"Élton",gols:12} },
  { nome:"Joel Santana",            jogos:102, casa:50, fora:52, v:48, e:25, d:29, gp:159, gc:124, saldo:35, aprov:55.2, maior_goleador:{nome:"Romário",gols:25} },
  { nome:"Antônio Lopes",           jogos: 93, casa:47, fora:46, v:43, e:19, d:31, gp:166, gc:132, saldo:34, aprov:53.0, maior_goleador:{nome:"Ramon",gols:15} },
  { nome:"Dorival Júnior",          jogos: 76, casa:34, fora:42, v:36, e:21, d:19, gp:121, gc: 82, saldo:39, aprov:56.6, maior_goleador:{nome:"Élton",gols:12} },
  { nome:"Ricardo Gomes",           jogos: 75, casa:39, fora:36, v:36, e:22, d:17, gp:132, gc: 84, saldo:48, aprov:57.8, maior_goleador:{nome:"Bernardo",gols:18} },
  { nome:"Zé Ricardo",              jogos: 73, casa:39, fora:34, v:33, e:21, d:19, gp: 97, gc: 79, saldo:18, aprov:54.8, maior_goleador:{nome:"Andrés Ríos",gols:12} },
  { nome:"Cristóvão Borges",        jogos: 71, casa:37, fora:34, v:39, e:14, d:18, gp:114, gc: 77, saldo:37, aprov:61.5, maior_goleador:{nome:"Alecsandro",gols:13} },
  { nome:"Fernando Diniz",          jogos: 69, casa:36, fora:33, v:21, e:20, d:28, gp: 89, gc: 97, saldo:-8, aprov:40.1, maior_goleador:{nome:"Rayan",gols:19} },
  { nome:"Valdir Espinosa",         jogos: 57, casa:30, fora:27, v:22, e:17, d:18, gp: 84, gc: 72, saldo:12, aprov:48.5, maior_goleador:{nome:"Leandro Amaral",gols:10} },
  { nome:"Evaristo de Macedo",      jogos: 51, casa:26, fora:25, v:25, e:14, d:12, gp:100, gc: 70, saldo:30, aprov:58.2, maior_goleador:{nome:"Romário",gols:26} },
  { nome:"Abel Braga",              jogos: 47, casa:23, fora:24, v:22, e:13, d:12, gp: 78, gc: 46, saldo:32, aprov:56.0, maior_goleador:{nome:"Romário",gols:20} },
  { nome:"Ramón Díaz",              jogos: 45, casa:22, fora:23, v:20, e:12, d:13, gp: 63, gc: 53, saldo:10, aprov:53.3, maior_goleador:{nome:"Pablo Vegetti",gols:18} },
  { nome:"Oswaldo de Oliveira",     jogos: 42, casa:22, fora:20, v:21, e: 9, d:12, gp: 69, gc: 56, saldo:13, aprov:57.1, maior_goleador:{nome:"Romário",gols:25} },
  { nome:"Geninho",                 jogos: 41, casa:20, fora:21, v:18, e:11, d:12, gp: 57, gc: 45, saldo:12, aprov:52.8, maior_goleador:{nome:"Valdir",gols:14} },
  { nome:"Vanderlei Luxemburgo",    jogos: 37, casa:18, fora:19, v:13, e:13, d:11, gp: 39, gc: 37, saldo: 2, aprov:46.8, maior_goleador:{nome:"Yago Pikachu",gols:6} },
  { nome:"Vagner Mancini",          jogos: 35, casa:17, fora:18, v:18, e: 7, d:10, gp: 55, gc: 37, saldo:18, aprov:58.1, maior_goleador:{nome:"Dodô",gols:11} },
  { nome:"Hélio dos Anjos",          jogos: 33, casa:18, fora:15, v:12, e:11, d:10, gp: 68, gc: 47, saldo:21, aprov:47.5, maior_goleador:{nome:"Romário",gols:22} },
  { nome:"Rafael Paiva",            jogos: 31, casa:15, fora:16, v:12, e: 8, d:11, gp: 37, gc: 39, saldo:-2, aprov:47.3, maior_goleador:{nome:"Pablo Vegetti",gols:8} },
  { nome:"Marcelo Cabo",            jogos: 31, casa:15, fora:16, v:13, e:10, d: 8, gp: 42, gc: 33, saldo: 9, aprov:52.7, maior_goleador:{nome:"Germán Cano",gols:13} },
  { nome:"Maurício Barbieri",       jogos: 29, casa:14, fora:15, v:10, e: 6, d:13, gp: 40, gc: 37, saldo: 3, aprov:41.4, maior_goleador:{nome:"Pedro Raul",gols:9} },
  { nome:"Milton Mendes",           jogos: 28, casa:15, fora:13, v:11, e: 6, d:11, gp: 30, gc: 39, saldo:-9, aprov:46.4, maior_goleador:{nome:"Luis Fabiano",gols:6} },
  { nome:"PC Gusmão",               jogos: 24, casa:13, fora:11, v: 9, e:12, d: 3, gp: 32, gc: 23, saldo: 9, aprov:54.2, maior_goleador:{nome:"Éder Luís",gols:8} },
  { nome:"Adilson Batista",         jogos: 24, casa:12, fora:12, v:11, e:10, d: 3, gp: 40, gc: 18, saldo:22, aprov:59.7, maior_goleador:{nome:"Edmilson",gols:11} },
  { nome:"Alberto Valentim",        jogos: 22, casa:12, fora:10, v:14, e: 4, d: 4, gp: 32, gc: 18, saldo:14, aprov:69.7, maior_goleador:{nome:"Marrony",gols:5} },
  { nome:"Fábio Carille",           jogos: 21, casa:11, fora:10, v: 9, e: 5, d: 7, gp: 28, gc: 21, saldo: 7, aprov:50.8, maior_goleador:{nome:"Pablo Vegetti",gols:14} },
  { nome:"Paulo Autuori",           jogos: 20, casa:10, fora:10, v: 9, e: 5, d: 6, gp: 34, gc: 30, saldo: 4, aprov:53.3, maior_goleador:{nome:"Tenorio",gols:5} },
  { nome:"Ramon Menezes",           jogos: 18, casa: 9, fora: 9, v: 8, e: 4, d: 6, gp: 23, gc: 21, saldo: 2, aprov:51.9, maior_goleador:{nome:"Germán Cano",gols:11} },
  { nome:"Gaúcho",                  jogos: 18, casa:11, fora: 7, v: 9, e: 2, d: 7, gp: 27, gc: 23, saldo: 4, aprov:53.7, maior_goleador:{nome:"Bernardo",gols:7} },
  { nome:"Ricardo Sá Pinto",        jogos: 17, casa: 9, fora: 8, v: 3, e: 6, d: 8, gp: 11, gc: 23, saldo:-12, aprov:29.4, maior_goleador:{nome:"Germán Cano",gols:5} },
  { nome:"Alfredo Sampaio",         jogos: 16, casa: 7, fora: 9, v:10, e: 1, d: 5, gp: 40, gc: 19, saldo:21, aprov:64.6, maior_goleador:{nome:"Alan Kardec",gols:7} },
  { nome:"Doriva",                  jogos: 15, casa: 8, fora: 7, v: 9, e: 3, d: 3, gp: 24, gc: 10, saldo:14, aprov:66.7, maior_goleador:{nome:"Gilberto",gols:5} },
  { nome:"Mauro Galvão",            jogos: 13, casa: 6, fora: 7, v: 2, e: 5, d: 6, gp: 17, gc: 21, saldo:-4, aprov:28.2, maior_goleador:{nome:"Valdir",gols:4} },
  { nome:"Lisca",                   jogos: 13, casa: 6, fora: 7, v: 4, e: 2, d: 7, gp: 15, gc: 19, saldo:-4, aprov:35.9, maior_goleador:{nome:"Marquinhos Gabriel",gols:3} },
  { nome:"Marcelo Oliveira",        jogos: 11, casa: 5, fora: 6, v: 3, e: 2, d: 6, gp: 10, gc: 17, saldo:-7, aprov:33.3, maior_goleador:{nome:"Carlos Alberto",gols:2} },
  { nome:"Emílio Faro (interino)",   jogos: 10, casa: 5, fora: 5, v: 5, e: 1, d: 4, gp: 15, gc: 12, saldo: 3, aprov:53.3, maior_goleador:{nome:"Andrey Santos",gols:5} },
  { nome:"Alcir Portela",           jogos:  9, casa: 4, fora: 5, v: 4, e: 3, d: 2, gp: 11, gc: 11, saldo: 0, aprov:55.6, maior_goleador:{nome:"Romário",gols:8} },
  { nome:"Maurício Souza",          jogos:  8, casa: 3, fora: 5, v: 3, e: 2, d: 3, gp:  7, gc:  7, saldo: 0, aprov:45.8, maior_goleador:{nome:"Raniel",gols:5} },
  { nome:"Felipe (interino)",       jogos:  7, casa: 3, fora: 4, v: 2, e: 2, d: 3, gp:  9, gc: 11, saldo:-2, aprov:38.1, maior_goleador:{nome:"Pablo Vegetti",gols:4} },
  { nome:"Romário",                 jogos:  5, casa: 3, fora: 2, v: 3, e: 1, d: 1, gp:  8, gc:  4, saldo: 4, aprov:66.7, maior_goleador:{nome:"Leandro Bonfim",gols:2} },
  { nome:"Marcos Valadares",        jogos:  5, casa: 3, fora: 2, v: 1, e: 1, d: 3, gp:  5, gc: 11, saldo:-6, aprov:26.7, maior_goleador:{nome:"Maxi López",gols:2} },
  { nome:"Álvaro Pacheco",          jogos:  4, casa: 2, fora: 2, v: 0, e: 1, d: 3, gp:  1, gc: 10, saldo:-9, aprov: 8.3, maior_goleador:{nome:"Pablo Vegetti",gols:1} },
  { nome:"Rafael Paiva (interino)", jogos:  4, casa: 2, fora: 2, v: 1, e: 2, d: 1, gp:  5, gc:  5, saldo: 0, aprov:41.7, maior_goleador:{nome:"Pablo Vegetti",gols:3} },
  { nome:"William Batista (interino)", jogos: 3, casa: 2, fora: 1, v: 1, e: 0, d: 2, gp: 1, gc: 3, saldo:-2, aprov:33.3, maior_goleador:{nome:"Jair",gols:1} },
  { nome:"Valdir Bigode",           jogos:  3, casa: 1, fora: 2, v: 1, e: 1, d: 1, gp:  2, gc:  2, saldo: 0, aprov:55.6, maior_goleador:{nome:"Andrey",gols:1} },
  { nome:"Ramon Lima",              jogos:  3, casa: 1, fora: 2, v: 0, e: 3, d: 0, gp:  2, gc:  2, saldo: 0, aprov:33.3, maior_goleador:{nome:"Paulo Ricardo",gols:1} },
  { nome:"Tita",                    jogos:  2, casa: 1, fora: 1, v: 1, e: 0, d: 1, gp:  3, gc:  2, saldo: 1, aprov:50.0, maior_goleador:{nome:"Viola",gols:1} },
  { nome:"Bruno Lazaroni (interino)", jogos:2, casa: 0, fora: 2, v: 0, e: 1, d: 1, gp:  2, gc:  3, saldo:-1, aprov:16.7, maior_goleador:{nome:"Cauan Barros",gols:1} },
  { nome:"Amilton Oliveira",        jogos:  1, casa: 0, fora: 1, v: 1, e: 0, d: 0, gp:  1, gc:  0, saldo: 1, aprov:100.0, maior_goleador:{nome:"Bruno Meneghel",gols:1} },
  { nome:"Marcelo Salles",          jogos:  0, casa: 0, fora: 0, v: 0, e: 0, d: 0, gp:  0, gc:  0, saldo: 0, aprov: 0.0, maior_goleador:null },
  { nome:"Alexandre Mendes",        jogos:  0, casa: 0, fora: 0, v: 0, e: 0, d: 0, gp:  0, gc:  0, saldo: 0, aprov: 0.0, maior_goleador:null },
];

// passagens detalhadas de Renato Gaúcho (do segundo print)
window.PASSAGENS_TECNICOS = {
  "Renato Gaúcho": {
    resumo: { jogos:151, v:68, e:45, d:38 },
    passagens: [
      { idx:1, jogos:26, v:10, e:10, d: 6, gp: 50, gc: 43, saldo:  7, aprov:51.3, artilheiro:{nome:"Alex Dias", gols:16}, periodo:"2005" },
      { idx:2, jogos:57, v:29, e:18, d:10, gp:122, gc: 78, saldo: 44, aprov:61.4, artilheiro:{nome:"Romário",  gols:27}, periodo:"2007-2008" },
      { idx:3, jogos:31, v:15, e: 8, d: 8, gp: 75, gc: 44, saldo: 31, aprov:57.0, artilheiro:{nome:"Romário",  gols:15}, periodo:"2008" },
      { idx:4, jogos:20, v: 6, e: 3, d:11, gp: 26, gc: 36, saldo:-10, aprov:35.0, artilheiro:{nome:"Edmundo",  gols: 6}, periodo:"2009" },
      { idx:5, jogos:17, v: 8, e: 6, d: 3, gp: 28, gc: 20, saldo:  8, aprov:58.8, artilheiro:{nome:"Thiago Mendes", gols:4}, periodo:"2026 – atual" },
    ],
    // amostra de jogos da primeira passagem (1)
    jogos: [
      { data:"23/01/2005", local:"casa", competicao:"Campeonato Carioca",            adv:"Portuguesa",       res:"V", placar:"Vasco 2 x 1 Portuguesa", passagem:1 },
      { data:"26/01/2005", local:"fora", competicao:"Campeonato Carioca",            adv:"América",          res:"E", placar:"Vasco 1 x 1 América",    passagem:1 },
      { data:"30/01/2005", local:"casa", competicao:"Campeonato Carioca",            adv:"Botafogo",         res:"E", placar:"Vasco 1 x 1 Botafogo",   passagem:1 },
      { data:"03/02/2005", local:"fora", competicao:"Campeonato Carioca",            adv:"Volta Redonda-RJ", res:"D", placar:"Vasco 0 x 1 Volta Redonda-RJ", passagem:1 },
      { data:"09/02/2005", local:"casa", competicao:"Campeonato Carioca",            adv:"Friburguense",     res:"V", placar:"Vasco 4 x 1 Friburguense",passagem:1 },
      { data:"16/02/2005", local:"fora", competicao:"Copa do Brasil",                adv:"União Rondonópolis-MT", res:"E", placar:"Vasco 2 x 2 União Rondonópolis-MT", passagem:1 },
      { data:"24/02/2005", local:"casa", competicao:"Campeonato Carioca",            adv:"Madureira-RJ",     res:"E", placar:"Vasco 3 x 3 Madureira-RJ", passagem:1 },
      { data:"27/02/2005", local:"casa", competicao:"Campeonato Carioca",            adv:"Fluminense-RJ",    res:"V", placar:"Vasco 2 x 1 Fluminense-RJ", passagem:1 },
      { data:"02/03/2005", local:"casa", competicao:"Copa do Brasil",                adv:"União Rondonópolis-MT", res:"V", placar:"Vasco 2 x 0 União Rondonópolis-MT", passagem:1 },
      { data:"06/03/2005", local:"fora", competicao:"Campeonato Carioca",            adv:"Cabofriense-RJ",   res:"D", placar:"Vasco 2 x 3 Cabofriense-RJ", passagem:1 },
      { data:"10/03/2005", local:"fora", competicao:"Copa do Brasil",                adv:"Moto Clube-MA",    res:"V", placar:"Vasco 2 x 1 Moto Clube-MA", passagem:1 },
      { data:"13/03/2005", local:"casa", competicao:"Campeonato Carioca",            adv:"Americano-RJ",     res:"V", placar:"Vasco 2 x 0 Americano-RJ", passagem:1 },
      { data:"16/03/2005", local:"casa", competicao:"Copa do Brasil",                adv:"Moto Clube-MA",    res:"V", placar:"Vasco 6 x 0 Moto Clube-MA", passagem:1 },
      { data:"20/03/2005", local:"casa", competicao:"Campeonato Carioca",            adv:"Flamengo-RJ",      res:"E", placar:"Vasco 2 x 2 Flamengo-RJ", passagem:1 },
      { data:"23/03/2005", local:"fora", competicao:"Campeonato Carioca",            adv:"Olaria-RJ",        res:"V", placar:"Vasco 2 x 1 Olaria-RJ", passagem:1 },
      { data:"26/03/2005", local:"fora", competicao:"Campeonato Carioca",            adv:"Fluminense-RJ",    res:"E", placar:"Vasco 1 x 1 Fluminense-RJ", passagem:1 },
      { data:"14/04/2005", local:"fora", competicao:"Copa do Brasil",                adv:"Baraúnas-RN",      res:"E", placar:"Vasco 2 x 2 Baraúnas-RN", passagem:1 },
      { data:"20/04/2005", local:"casa", competicao:"Copa do Brasil",                adv:"Baraúnas-RN",      res:"D", placar:"Vasco 0 x 3 Baraúnas-RN", passagem:1 },
      { data:"24/04/2005", local:"fora", competicao:"Campeonato Brasileiro Série A", adv:"Brasiliense-DF",   res:"V", placar:"Vasco 1 x 0 Brasiliense-DF", passagem:1 },
      { data:"30/04/2005", local:"casa", competicao:"Campeonato Brasileiro Série A", adv:"Fortaleza-CE",     res:"E", placar:"Vasco 0 x 0 Fortaleza-CE", passagem:1 },
      { data:"15/05/2005", local:"fora", competicao:"Campeonato Brasileiro Série A", adv:"Juventude-RS",     res:"D", placar:"Vasco 1 x 4 Juventude-RS", passagem:1 },
      { data:"22/05/2005", local:"casa", competicao:"Campeonato Brasileiro Série A", adv:"São Paulo-SP",     res:"V", placar:"Vasco 3 x 1 São Paulo-SP", passagem:1 },
      { data:"29/05/2005", local:"fora", competicao:"Campeonato Brasileiro Série A", adv:"Ponte Preta-SP",   res:"D", placar:"Vasco 2 x 4 Ponte Preta-SP", passagem:1 },
      { data:"12/06/2005", local:"casa", competicao:"Campeonato Brasileiro Série A", adv:"Coritiba-PR",      res:"E", placar:"Vasco 2 x 2 Coritiba-PR", passagem:1 },
      { data:"18/06/2005", local:"fora", competicao:"Campeonato Brasileiro Série A", adv:"Palmeiras-SP",     res:"D", placar:"Vasco 2 x 5 Palmeiras-SP", passagem:1 },
      { data:"26/06/2005", local:"fora", competicao:"Campeonato Brasileiro Série A", adv:"Cruzeiro-MG",      res:"E", placar:"Vasco 3 x 3 Cruzeiro-MG", passagem:1 },
    ],
  },
};
